Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -62,7 +62,18 @@ jobs:
 
     - name: Install Android SDK packages
       run: |
-        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
+        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;default;x86_64"
+      shell: bash
+
+    - name: Verify aidl installation
+      run: |
+        if ! command -v aidl &> /dev/null
+        then
+            echo "aidl could not be found"
+            exit 1
+        else
+            echo "aidl found"
+        fi
       shell: bash
 
     - name: Build APK
