Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,5 @@
 name: Build
+
 on:
   push:
     branches-ignore:
@@ -41,6 +42,34 @@ jobs:
           source venv/bin/activate
           python --version
 
+      - name: Install dependencies
+        run: |
+          source venv/bin/activate
+          pip install buildozer
+
+      - name: Install Android SDK
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y wget unzip
+          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
+          mkdir -p $HOME/android-sdk/cmdline-tools
+          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
+          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
+          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
+          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
+          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
+          sdkmanager --sdk_root=$HOME/android-sdk --install "platform-tools" "platforms;android-30"
+          yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
+
+      - name: Check if AIDL is installed
+        run: |
+          if ! command -v aidl &> /dev/null
+          then
+              echo "aidl could not be found"
+              exit 1
+          else
+              echo "aidl found"
+          fi
 
       - name: Build with Buildozer
         uses: ArtemSBulgakov/buildozer-action@v1
@@ -56,7 +85,7 @@ jobs:
           name: package
           path: ${{ steps.buildozer.outputs.filename }}
 
-      - name: Checkout
+      - name: Checkout data branch
         uses: actions/checkout@v2
         with:
           path: data
